version: '2'

services:

    seleniumhub:
      image: selenium/hub
      ports:
         - 4446:4444
         
    chromenode1:
      image: selenium/node-chrome-debug
      ports:
        - 4578
      links:
       -  seleniumhub:hub

    chromenode2:
      image: selenium/node-chrome-debug
      ports:
        - 4579
      links:
        - seleniumhub:hub
    
    firefoxnode:
      image: selenium/node-firefox-debug
      ports:
        - 4577
      links:
      -  seleniumhub:hub